[project]
name = 'Cosmic-Energy-Redistribution-Network--CERN-'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.civilization-energy-allocation]
path = 'contracts/civilization-energy-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.stellar-energy-harvesting]
path = 'contracts/stellar-energy-harvesting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
